name: school
services:

  api:
    container_name: school_api

    build:
      context: ./fastapi
      dockerfile: Dockerfile_fastapi

    volumes:
      - ./database:/fastapi/database          # HOST_PATH:CONTAINER_PATH

    ports:
      - "8080:80"   # на хосте 8080 → в контейнере 80

    restart: always
