name: school
services:

  api:
    container_name: school_api

    build:
      context: ./fastapi
      dockerfile: Dockerfile_fastapi

    volumes:
      - ./database:/fastapi/database
   
    networks:
      mynet:
        ipv4_address: 172.22.0.15

    restart: always
  
  cli:
    container_name: school_vue
    build:
      context: ./vue
      dockerfile: Dockerfile_vue
    profiles:
      - cli
    networks:
      mynet:
        ipv4_address: 172.22.0.16
    restart: always

networks:
  mynet:
    name: vps_mynet
    external: true
