FROM python:3.11-buster

WORKDIR /fastapi

ENV PATH="${PATH}:/root/.local/bin"
ENV PYTHONPATH=.

COPY requirements.txt ./

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY src src/

CMD ["fastapi", "run", "src/main.py", "--port", "8081"]
