@startuml schd_erd
'https://plantuml.com/object-diagram
'Opt+D to Preview

<style>
    document {
        BackGroundColor Linen
    }
    root {
        FontColor #?black:white
        LineColor gray
    }
</style>

title SCHD_ERD

object Lessons {
    *id: PK
    *lessonNum
    subjectId: FK
    subject
    weekdayId: FK
    weekday
}

object Subjects {
    *id: PK
    *name
    *lessons[]
}

object Weekdays {
    *id:PK
    *dayNum
    *dayName
    lessons[]
}


Subjects::id ||-l-o{ Lessons::subjectId
Weekdays::id ||-r-o{ Lessons::weekdayId

@enduml
